[package]
name = "gentoo-kernel-builder"
version = "0.1.0"
edition = "2021"
authors = ["koopa1338 <sinner1991@gmail.com"]
license-file = "LICENSE.md"
description = "select kernel version from available sources, build and install"

[dependencies]
dialoguer = "0.10"
nix = "0.26"
